#!/bin/bash

if [[ $# -eq 1 ]]
	then
		DEF="$1("
		RES_DEF="$(grep -rin $DEF * | grep "*.c*" | grep -v ";" | sed 's/:/ | line = /' | sed 's/:/ --> /')"
		if [ -n "$RES_DEF" ]
			then 
				echo "Definition possibly here : "
				printf "${RES_DEF}\n\n"
		fi
		OUT="$(grep -rin $1 * | cut -d: -f1-2 | sed 's/:/ | line : /g')"
		if [ -z "$OUT" ]
			then
				echo "No occurence in this dir and sub dir"
			else
				echo "occurences : "
				echo "${OUT}"
		fi
	else
		echo "usage : ./03 <string>"
fi
